services:
- type: web
  name: gestionale-ncc
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  disk:
    name: ncc-database
    mountPath: /opt/render/project/src
    sizeGB: 1